---
- name: Compile redis
  command: make
  args:
    chdir: "{{ redis_home }}"
    creates: "{{ redis_home }}/src/redis-server"

- name: Add Redis's bin files to alternatives
  alternatives:
    name: "{{ item }}"
    path: "{{ redis_home }}/src/{{ item }}"
    link: "/usr/bin/{{ item }}"
  with_items:
  - redis-cli
  - redis-server
  - redis-trib.rb
