---
- name: Install dependencies tools
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - make
    - tcl
    - wget
    - tar
    - hugepages