---
- name: Add Brightbox ppa for Ruby 2.4
  apt_repository:
    repo: ppa:brightbox/ruby-ng

- name: Install dependencies tools
  apt:
    pkg: "{{ item }}"
    update_cache: yes
    cache_valid_time: 86400
    state: present
  with_items:
    - gcc
    - make
    - tcl
    - wget
    - tar
    - hugepages
    - ruby2.4

- name: Install Redis gem
  command: "gem install redis -v {{ redis_ruby_version }}"
