---
- name: Set up create cluster script
  template:
    src: "cluster/create.sh.j2"
    dest: "{{ redis_user_home }}/create.sh"
    owner: "{{ redis_user }}"
    mode: 0711
    force: yes
  notify: create cluster

- name: Set up assign slots script
  template:
    src: "cluster/assign_slots.sh.j2"
    dest: "{{ redis_user_home }}/assign_slots.sh"
    owner: "{{ redis_user }}"
    mode: 0711
    force: yes
  notify: assign hash slots



